"""Creacion inicial de tablas

Revision ID: 302241b8cfec
Revises: 
Create Date: 2025-11-01 01:08:30.488934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302241b8cfec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('vueltas', sa.Integer(), nullable=True),
    sa.Column('potencia_influencia', sa.Float(), nullable=True),
    sa.Column('aero_influencia', sa.Float(), nullable=True),
    sa.Column('manejo_influencia', sa.Float(), nullable=True),
    sa.Column('desgaste_neumaticos', sa.Float(), nullable=True),
    sa.Column('prob_safety_car', sa.Float(), nullable=True),
    sa.Column('prob_lluvia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('presupuesto', sa.Float(), nullable=True),
    sa.Column('reputacion', sa.Float(), nullable=True),
    sa.Column('base_tecnica', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('coches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=True),
    sa.Column('motor', sa.Float(), nullable=True),
    sa.Column('aerodinamica', sa.Float(), nullable=True),
    sa.Column('chasis', sa.Float(), nullable=True),
    sa.Column('fiabilidad', sa.Float(), nullable=True),
    sa.Column('desgaste_motor', sa.Float(), nullable=True),
    sa.Column('desgaste_caja', sa.Float(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    op.create_table('pilotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('velocidad', sa.Float(), nullable=True),
    sa.Column('consistencia', sa.Float(), nullable=True),
    sa.Column('riesgo', sa.Float(), nullable=True),
    sa.Column('experiencia', sa.Float(), nullable=True),
    sa.Column('feedback_tecnico', sa.Float(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('contrato_duracion', sa.Integer(), nullable=True),
    sa.Column('moral', sa.Float(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('habilidad', sa.Float(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('moral', sa.Float(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('pilotos')
    op.drop_table('coches')
    op.drop_table('equipos')
    op.drop_table('circuitos')
    # ### end Alembic commands ###
